version: '3.9'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432" # Maps the container's port 5432 to the host's port 5432
    environment:
      POSTGRES_USER: admin      # Custom username for PostgreSQL
      POSTGRES_PASSWORD: password # Custom password for PostgreSQL
      POSTGRES_DB: task_management_app    # Default database to create on startup

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025" # SMTP server port
      - "8025:8025" # Web UI port
